[package]
name = "k4a-sys"
version = "0.1.0"
authors = ["Amédée d'Aboville <amedee.daboville@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
description = "The Azure K4A API bindgen-ed to Rust."

[build-dependencies]
bindgen = "0.52.0"
